spring:
  application:
    name: GreengramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_v3
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
  cache:
    disabled: true
  api-docs:
    version: openapi_3_1

file:
  dir: D:\Students\BCH\file\greengram_ver3\